### ISSUE TITLE
Identification of inserted/deleted bases on tag name

### ISSUE THREAD

**Issue by gavinkurgan** [felicityallen/SelfTarget#4]
Hello Felicity!

So I have been utilizing FORECasT from the command line, but was wondering, is there any way to reconstruct the identity of the inserted/deleted bases without realigning the predicted read to original input? I saw that you have an extended tag name in the generated indel summary file, but can't seem to make heads or tails if the tag name has the information on which indices to extract to get this information.

For example I have the following:

```
-	-	1000
D7_L-9C3R2	-	121
```

Which corresponds to the following alignment
```
AAATTCCAGACAAGTTTGTTGTAGGATATGCCCTTGACTATAATGAATACTTCAGGGATTTGAATGTAAGTAATTGCTTCTTTTTCTCACTCATTTTTCA
AAATTCCAGACAAGTTTGTTGTAGGATATGCCCTTGACTATA-------CTTCAGGGATTTGAATGTAAGTAATTGCTTCTTTTTCTCACTCATTTTTCA
```

Could you shed some light on whether it is possible to use this tag name to extract indices of the deleted bases? If not, is there any reasoning to how this tag name is generated (besides the I#/D# portion)?

Thanks,
Gavin

**Comment by felicityallen** [comment]
Hi Gavin,

D = deletion. I = Insertion. The next number is the size. The part after the underscore tells you where the mutation was. L is the index (with respect to the cut site) of the leftmost unchanged nucleotide, and R is similarly for the right-most. C tells you the ambiguity, which is usually due to microhomolgy e.g. in the example you give there are 3 nucleotides 'ATA' that could be on either end of the deletion.

**Comment by gavinkurgan** [comment]
Great, that helps a lot. Thanks for addressing this so quickly!
